// <auto-generated />
namespace BlazorDungeonCrawler.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBSet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBSet));
        
        string IMigrationMetadata.Id
        {
            get { return "202310092110023_DBSet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
